### ISSUE TITLE
hierarchy from annotation has nan values

### ISSUE THREAD

**Issue by coleslaw481** [idekerlab/cellmaps_vnn#1]
The attached hierarchy 
[hierarchy.cx2.gz](https://github.com/idekerlab/cellmaps_vnn/files/15255390/hierarchy.cx2.gz)

has `nan` values for `pho_Rho` column because training was not run long enough. Should catch this and return an error and 
say there was not sufficient training.

**Comment by dzoanka** [comment]
done on dev
